### ISSUE TITLE
error: Uncaught AddrNotAvailable: Cannot assign requested address (os error 99)

### ISSUE THREAD

**Issue by F1nx** [F1nx/double-whammy-protocol#4]
> `error: Uncaught AddrNotAvailable: Cannot assign requested address (os error 99)`
    `at unwrapResponse (rt/10_dispatch_json.js:25:13)`
    `at sendSync (rt/10_dispatch_json.js:52:12)`
    `at opListen (rt/30_net.js:33:12)`
    `at Object.listen (rt/30_net.js:204:17)`
    `at serve (server.ts:287:25)`
    `at server (index.ts:125:28)`

**Comment by Zacharys-Hackery** [comment]
Could have to do with `IPv4` or the user's permissions set on their computer.

**Comment by Zacharys-Hackery** [comment]
Noted that we are trying to write a protocol, so we could look for something bare-boned with Deno. Looks like it's file server would be appealing as well.

**Comment by F1nx** [comment]
Focus shifted to just the algorithm.
